allowBuilds:
  aws-sdk: true
  esbuild: true
  serverless: true
minimumReleaseAgeExclude:
  - '@aws-sdk/client-dynamodb@3.1057.0'
  - '@aws-sdk/credential-provider-ini@3.972.46'
  - '@aws-sdk/credential-provider-node@3.972.47'
  - '@aws-sdk/lib-dynamodb@3.1057.0'
  - '@smithy/credential-provider-imds@4.3.6'
