allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  serverless: true
minimumReleaseAgeExclude:
  - '@aws-sdk/client-dynamodb@3.1056.0'
  - '@aws-sdk/core@3.974.15'
  - '@aws-sdk/credential-provider-env@3.972.41'
  - '@aws-sdk/credential-provider-http@3.972.43'
  - '@aws-sdk/credential-provider-ini@3.972.45'
  - '@aws-sdk/credential-provider-login@3.972.45'
  - '@aws-sdk/credential-provider-node@3.972.46'
  - '@aws-sdk/credential-provider-process@3.972.41'
  - '@aws-sdk/credential-provider-sso@3.972.45'
  - '@aws-sdk/credential-provider-web-identity@3.972.45'
  - '@aws-sdk/dynamodb-codec@3.973.15'
  - '@aws-sdk/lib-dynamodb@3.1056.0'
  - '@aws-sdk/middleware-endpoint-discovery@3.972.15'
  - '@aws-sdk/nested-clients@3.997.13'
  - '@aws-sdk/signature-v4-multi-region@3.996.30'
  - '@aws-sdk/token-providers@3.1056.0'
